package com.musicstreaming.application.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a user of the music streaming application.
 * This entity contains the user's authentication and profile information,
 * and is mapped to the "users" table in the database.
 *
 * Lombok's @Data annotation is used to automatically generate
 * getters, setters, toString, equals, and hashCode methods.
 */
@Entity
@Data
@Table(name = "users")
public class User {

    /**
     * The unique identifier for the user.
     * This value is automatically generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user's email address.
     * Typically used as a unique identifier for login or communication.
     */
    private String email;

    /**
     * The username chosen by the user.
     */
    private String username;

    /**
     * The user's password.
     * Note: In a production environment, this should be stored in a securely hashed format.
     */
    private String password;

    /**
     * The role assigned to the user.
     * Defaults to "ROLE_USER".
     */
    private String role = "ROLE_USER";
}
